name: Docker

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.REGISTRY_USERNAME}}
        password: ${{secrets.REGISTRY_PASSWORD}}
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: make push
