name: Docker

env:
  DOCKERHUB_REPO: flyskype2021/ducker

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{secrets.REGISTRY_USERNAME}}
        password: ${{secrets.REGISTRY_PASSWORD}}

    - name: Sync README To DockerHub
      uses: meeDamian/sync-readme@v1.0.6
      with:
        user: ${{secrets.REGISTRY_USERNAME}}
        pass: ${{secrets.REGISTRY_PASSWORD}}
        slug: ${{ env.DOCKERHUB_REPO }}
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: make push
